### ISSUE TITLE
[Bug]: Incorrect content for JS V6 card on Ethers Getting Started page

### ISSUE THREAD

**Issue by itsacoyote** [zksync-sdk/sdk-docs#45]
### What happened?

On the JS Ethers Getting Started page (https://docs.zksync.io/sdk/js/ethers), the card for V6 has the wrong message content. It says "Integrate zksync Go SDK for zkSync Era features.". 

---
screenshot of cards:
![Screenshot 2024-06-11 at 9 51 24 AM](https://github.com/zksync-sdk/sdk-docs/assets/812331/09631cce-be36-43e2-9e39-94aea358933d)

### What did you expect to happen?

It should say "Integrate zksync-ethers JS SDK for zkSync Era features.".  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ngozi-Txfusion** [comment]
That was a typo, and Its resolved.
Thank you
